DEBUG = True

IMAGE_WIDTH_SIZE = 800
IMAGE_HEIGHT_SIZE = 600

# Preprocess Image
NONEZERO_PARAM = 10
DILATE_ERODE_ITER_PARAM = 10

# Find Plate
LEFT_OFFSET = -6
RIGHT_OFFSET = 0
TOP_OFFSET = 0
BOTTOM_OFFSET = 0

MIN_ACREAGE_RATIO = 30
MAX_ACREAGE_RATIO = 270

MIN_WIDTH_HEIGHT_RATIO = 2.6
MAX_WIDTH_HEIGHT_RATIO = 7
MIN_WIDTH = 80
MAX_WIDTH = 250
MIN_HEIGHT = 25
MAX_HEIGHT = 150

# Find character Parameter
CHAR_HEIGHT_RESIZE = 408
CHAR_WIDTH_RESIZE = 70
CHAR_MIN_WIDTH = 15
CHAR_MAX_WIDTH = 50
CHAR_MIN_HEIGHT = 40
CHAR_MAX_HEIGHT = 65
MIN_WH = 850
CHAR_MIN_WH_RATIO = 0.3
CHAR_MAX_WH_RATIO = 1.1
CHAR_MIN_RATIO_WHITE = 0.3
CHAR_MAX_RATIO_WHITE = 0.75
